name: smart_irrigation
description: A smart irrigation system controller.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #dependency injection
  get_it: ^7.2.0

  # state management
  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1

  #DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Network and API
  cached_network_image: ^3.2.0 
  http: 

  # utils
  validators: ^3.0.0
  flutter_svg: ^1.1.6
  youtube_player_flutter: ^8.1.1
  flutter_inappwebview: ^5.7.2

  #animation
  supercharged: ^2.1.1
  simple_animations: ^5.0.0+2
  vector_math: 



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.2 


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
